# This workflow will build and upload packages to PyPI when a new release is created.
# It is based on the "standard" Github workflow and uses twine to do the upload.
# Read more about the Twine Github Action at https://github.com/pypa/gh-action-pypi-publish

name: Upload package to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      # Required for
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
